{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "al-5g-ae.fullname" . }}-api-keys
  labels:
    {{- include "al-5g-ae.labels" . | nindent 4 }}
type: Opaque
data:
  api-keys: {{ .Values.auth.apiKeys | b64enc | quote }}
{{- end }}
---
{{- if and .Values.components.slackBot (not .Values.slack.existingSecret) }}
{{- if or .Values.slack.botToken .Values.slack.appToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "al-5g-ae.fullname" . }}-slack
  labels:
    {{- include "al-5g-ae.labels" . | nindent 4 }}
type: Opaque
data:
  bot-token: {{ .Values.slack.botToken | b64enc | quote }}
  app-token: {{ .Values.slack.appToken | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- if and .Values.components.teamsBot (not .Values.teams.existingSecret) }}
{{- if or .Values.teams.appId .Values.teams.appPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "al-5g-ae.fullname" . }}-teams
  labels:
    {{- include "al-5g-ae.labels" . | nindent 4 }}
type: Opaque
data:
  app-id: {{ .Values.teams.appId | b64enc | quote }}
  app-password: {{ .Values.teams.appPassword | b64enc | quote }}
{{- end }}
{{- end }}
